version: '3.8'

services:
  task-manager:
    image: rohitxten/task-manager:latest
    ports:
      - "8081:8081"    
      - "19000:19000"   
      - "19001:19001"  
      - "19002:19002"  
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    stdin_open: true
    tty: true
    command: npx expo start --tunnel